import "server-only";

import { timingSafeEqual } from "node:crypto";
import { Buffer } from "node:buffer";

import { deriveDisplayTitle } from "@/lib/server/transcripts/display-title";
import { isShareSuppressedByRestore, isWorkspaceActive } from "@/lib/server/workspaces/archival-state";

import { PublicShareResolutionRefusedError } from "./errors";
import { findTranscriptByPublicShareId, type PublicShareLookupView } from "./queries";

// Resolution service for the `/share/:publicShareId/:shareSecretId`
// public route. The caller is always unauthenticated from the
// capability's perspective — even a signed-in workspace member that
// happens to open this URL gets the same privacy-minimal view, per
// the "public page remains read-only even when the viewer is also
// signed in" spec requirement.
//
// Every refusal path raises `PublicShareResolutionRefusedError` with
// a specific `reason` so the caller can emit a rich server log, but
// the HTTP response MUST always collapse those reasons to the same
// generic 404/unavailable presentation. The route handler is
// responsible for that collapse; this service stays verbose in its
// internal vocabulary so tests can assert which refusal branch
// fired.
//
// Validation order (each step aborts with its own reason on miss):
//
//   1. Both path segments are UUID-shaped. Any malformed shape is
//      collapsed to `unknown_share_id` so the resolver cannot leak
//      "this looked like a real UUID but didn't match a record"
//      from "this wasn't a UUID at all".
//   2. A transcript with the given `publicShareId` exists; a miss
//      also surfaces as `unknown_share_id`.
//   3. Workspace is currently active (`archivedAt === null`). An
//      archived workspace returns `workspace_inactive` regardless of
//      share state. This keeps the archival lifecycle rule in one
//      place — the share surface defers to `isWorkspaceActive`.
//   4. Post-restore suppression: a restored workspace whose share
//      has not been touched since restore stays unavailable until a
//      `member`/`admin` runs a fresh share-management action, per
//      `isShareSuppressedByRestore`. Returns `workspace_inactive`
//      to match the generic archive-driven treatment.
//   5. Share is currently enabled for the transcript.
//   6. The URL's secret segment matches the transcript's active
//      `shareSecretId` exactly. Constant-time comparison keeps
//      future timing-attack defenses simple; for now the check is
//      a normalized string compare.
//   7. Transcript is still in `completed` status. A record that is
//      somehow no longer complete is treated as unavailable rather
//      than exposing in-flight content.

export type PublicShareResolveInputs = {
  publicShareId: string;
  shareSecretId: string;
  now?: Date;
};

export type PublicShareView = {
  displayTitle: string;
  recapMarkdown: string;
  transcriptMarkdown: string;
};

// RFC 4122 UUID regex (accepts any version and any variant, since the
// share identifiers are generated by `randomUUID` which always emits
// v4, but the resolver stays permissive enough that a future rotation
// to a new algorithm does not break old links). Lowercased because
// `randomUUID` emits lower-case UUIDs — we normalize the URL input to
// lower case before matching so `/share/ABC.../DEF...` also resolves
// consistently.
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export async function resolvePublicShare(inputs: PublicShareResolveInputs): Promise<PublicShareView> {
  const publicShareId = normalizeSegment(inputs.publicShareId);
  const shareSecretId = normalizeSegment(inputs.shareSecretId);
  if (!UUID_REGEX.test(publicShareId) || !UUID_REGEX.test(shareSecretId)) {
    throw new PublicShareResolutionRefusedError("unknown_share_id");
  }

  const record = await findTranscriptByPublicShareId({ publicShareId });
  return validatePublicShareLookup({ record, shareSecretId, now: inputs.now ?? new Date() });
}

// Pure synchronous validator that takes the looked-up record (or
// null) and performs every step of the resolver's decision tree
// except the DB read. Split out from `resolvePublicShare` so tests
// can exercise the whole state machine — including workspace
// archival and post-restore suppression interactions — without
// having to stub the Drizzle client. The caller is responsible for
// normalizing and UUID-validating the URL segments before handing
// the secret in; the secret comparison here is a straight byte-for-
// byte `timingSafeEqual`.
export type ValidatePublicShareLookupInputs = {
  record: PublicShareLookupView | null;
  shareSecretId: string;
  now: Date;
};

export function validatePublicShareLookup(inputs: ValidatePublicShareLookupInputs): PublicShareView {
  const { record, shareSecretId, now } = inputs;
  if (!record) {
    throw new PublicShareResolutionRefusedError("unknown_share_id");
  }

  enforceWorkspaceAvailability(record, now);

  if (!record.isPubliclyShared) {
    throw new PublicShareResolutionRefusedError("share_disabled");
  }
  if (record.shareSecretId === null || !secretsEqual(record.shareSecretId, shareSecretId)) {
    throw new PublicShareResolutionRefusedError("secret_mismatch");
  }
  if (record.status !== "completed") {
    throw new PublicShareResolutionRefusedError("transcript_not_completed");
  }

  return {
    displayTitle: deriveDisplayTitle({ title: record.title, customTitle: record.customTitle }),
    recapMarkdown: record.recapMarkdown,
    transcriptMarkdown: record.transcriptMarkdown,
  };
}

function enforceWorkspaceAvailability(record: PublicShareLookupView, now: Date): void {
  const workspaceTimestamps = {
    archivedAt: record.workspaceArchivedAt,
    scheduledDeleteAt: record.workspaceScheduledDeleteAt,
    restoredAt: record.workspaceRestoredAt,
  };
  if (!isWorkspaceActive(workspaceTimestamps)) {
    throw new PublicShareResolutionRefusedError("workspace_inactive");
  }
  // Post-restore suppression needs a `shareUpdatedAt` value to
  // compare against `restoredAt`. If no share-management action has
  // ever run on this record, the share cannot be active anyway; we
  // skip the suppression check because the `isPubliclyShared` guard
  // below will refuse the request with the correct reason.
  if (record.shareUpdatedAt && isShareSuppressedByRestore({ workspace: workspaceTimestamps, shareUpdatedAt: record.shareUpdatedAt })) {
    throw new PublicShareResolutionRefusedError("workspace_inactive");
  }
  // `now` is not consumed here yet but is threaded through so future
  // per-request policies (e.g. time-bound shares, token expirations)
  // can hook in without changing call sites. Keeping the parameter
  // keeps the service's deterministic-test contract explicit.
  void now;
}

// Constant-time comparison of the stored `shareSecretId` against
// the candidate value from the URL. The length-check early-out is
// safe because the stored secret is always a 36-character UUID —
// revealing "the secret you supplied is the wrong length" does not
// give the attacker any advantage over the cheaper UUID_REGEX
// validation a few lines earlier. For identical-length inputs we
// fall through to `timingSafeEqual`, which compares every byte
// regardless of where the mismatch is.
function secretsEqual(active: string, candidate: string): boolean {
  const expected = Buffer.from(active, "utf8");
  const provided = Buffer.from(candidate, "utf8");
  if (expected.length !== provided.length) return false;
  return timingSafeEqual(expected, provided);
}

function normalizeSegment(raw: string): string {
  return raw.trim().toLowerCase();
}
